/**
 * @file Automatically generated by barrelsby.
 */

export * from './customization.component.spec';
export * from './customization.component';
export * from './customization.routes';
export * from './customization.service.spec';
export * from './customization.service';
